#!/usr/bin/env php
<?php

defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');

require_once __DIR__ . '/vendor/autoload.php';
require_once __DIR__ . '/vendor/yiisoft/yii2/Yii.php';

$config = yii\helpers\ArrayHelper::merge(
    require __DIR__ . '/tests/config.php',
    (@include __DIR__ . '/tests/config-local.php') ?: []
);

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
