#!/usr/bin/env php
<?php

use yii\helpers\ArrayHelper;

defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');

require_once __DIR__.'/vendor/autoload.php';
require_once __DIR__.'/vendor/yiisoft/yii2/Yii.php';

if (file_exists(__DIR__ . '/tests/config-local.php')) {
    $config = yii\helpers\ArrayHelper::merge(
        require(__DIR__ . '/tests/config.php'),
        require(__DIR__ . '/tests/config-local.php'),
        );
} else {
    $config = require(__DIR__.'/tests/config.php');
}

$application = new \yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
