name: CI

on: push

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
      - uses: mirromutth/mysql-action@v1.1
        with:
          character set server: 'utf8'
          collation server: 'utf8_general_ci'
          mysql version: '5.6'
          mysql database: autocrm_test
          mysql root password: qweasdzxc

      - uses: actions/checkout@v2

      - uses: shivammathur/setup-php@v2
        with:
          php-version: "7.3"
          coverage: xdebug
          tools: composer

      - run: composer install --prefer-dist --no-suggest --no-progress

      - run: php yii migrate/up --interactive=0

      - run: php vendor/bin/phpunit --configuration phpunit.xml.dist --bootstrap tests/bootstrap.php

      - uses: chekalsky/phpcs-action@v1
        with:
          phpcs_bin_path: './vendor/bin/phpcs'
