name: CI

on: push

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
      - uses: mirromutth/mysql-action@v1.1
        with:
          character set server: 'utf8'
          collation server: 'utf8_general_ci'
          mysql version: '5.6'
          mysql database: autocrm_test
          mysql root password: qweasdzxc

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.3"
          coverage: xdebug
          tools: composer

      - name: Determine composer cache directory
        run: echo "::set-env name=COMPOSER_CACHE_DIR::$(composer config cache-dir)"

      - name: Cache dependencies installed with composer
        uses: actions/cache@v2
        with:
          path: ${{ env.COMPOSER_CACHE_DIR }}
          key: php-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            php-composer-

      - name: Install dependencies with composer
        run: composer install --prefer-dist --no-suggest --no-progress

      - name: Apply migrations
        run: php yii migrate/up --interactive=0

      - name: Run unit tests
        run: php vendor/bin/phpunit --configuration phpunit.xml.dist --bootstrap tests/bootstrap.php --coverage-text --coverage-html=build/coverage

      - name: Static analysis with php codesniffer
        uses: chekalsky/phpcs-action@v1
        with:
          phpcs_bin_path: './vendor/bin/phpcs'
