name: CI

on: push

jobs:
  tests:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.6
        env:
          MYSQL_DATABASE: autocrm_test
          MYSQL_ROOT_PASSWORD: qweasdzxc
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
    steps:
      - uses: actions/checkout@v2

      - uses: php-actions/composer@v2

      - run: php yii migrate/up --interactive=0

      - run: php vendor/bin/phpunit --configuration phpunit.xml.dist --bootstrap tests/bootstrap.php
