name: CI

on: push

jobs:
  deploy:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.6
        env:
          MYSQL_ROOT_PASSWORD: ""
          MYSQL_DATABASE: autocrm
        ports:
          - 3306:3306

    steps:
      - uses: actions/checkout@v2

      - uses: php-actions/composer@v2

      - uses: php-actions/php-build@master
      - run: php yii migrate/up --interactive=0

      - uses: php-actions/phpunit@v9
        with:
          configuration: phpunit.xml.dist