name: CI

on: push

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
      - uses: mirromutth/mysql-action@v1.1
        with:
          character set server: 'utf8' # Optional, default value is 'utf8mb4'. The '--character-set-server' option for mysqld
          collation server: 'utf8_general_ci' # Optional, default value is 'utf8mb4_general_ci'. The '--collation-server' option for mysqld
          mysql version: '8.0' # Optional, default value is "latest". The version of the MySQL
          mysql database: 'autocrm_test' # Optional, default value is "test". The specified database which will be create
          mysql root password: qweasdzxc # Required if "mysql user" is empty, default is empty. The root superuser password

      - uses: actions/checkout@v2

      - uses: php-actions/composer@v2

      - run: php yii migrate/up --interactive=0

      - run: php vendor/bin/phpunit --configuration phpunit.xml.dist --bootstrap tests/bootstrap.php
