name: CI

on: push

env:
  MYSQL_ROOT_PASSWORD: qweasdzxc

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
      - uses: mirromutth/mysql-action@v1.1
        with:
          character set server: 'utf8'
          collation server: 'utf8_unicode_ci'
          mysql version: '8.0'
          mysql database: autocrm_test
          mysql root password: $MYSQL_ROOT_PASSWORD

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"
          coverage: xdebug
          tools: composer
          extensions: none, imap, soap, gd, mbstring, curl, dom, ftp, intl, pdo, xml, zip, simplexml, fileinfo, tokenizer, sockets, xmlreader, xmlwriter, pdo-mysql

      - name: Allow composer plugin
        run: composer config --no-plugins allow-plugins.yiisoft/yii2-composer true

      - name: Install dependencies with composer
        run: composer install --prefer-dist --no-progress

      - name: Wait for MySQL
        run: |
          while ! mysqladmin ping --host=127.0.0.1 --password=$MYSQL_ROOT_PASSWORD --silent; do
            sleep 1
          done

      - name: Apply migrations
        run: php yii migrate/up --interactive=0

      - name: Run unit tests
        run: php vendor/bin/phpunit --configuration phpunit.xml.dist --bootstrap tests/bootstrap.php --coverage-text --coverage-html=build/coverage

      - name: Static analysis with php codesniffer
        uses: chekalsky/phpcs-action@v1
        with:
          phpcs_bin_path: './vendor/bin/phpcs'
