name: CI

on: push

jobs:
  deploy:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.6
        env:
          MYSQL_DATABASE: autocrm
          MYSQL_ROOT_PASSWORD: qweasdzxc
        ports:
          - 3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v2

      - uses: php-actions/composer@v2

      - run: php yii migrate/up --interactive=0

      - uses: php-actions/phpunit@v9
        with:
          configuration: phpunit.xml.dist